version: '3.8'

# Shared configuration for all environments
x-base-config: &base-config
  ports:
    - "11235:11235"  # Gunicorn port
  environment:
    - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    - LLM_PROVIDER=${LLM_PROVIDER:-}
    # The SECURITY_API_KEYS variable is still needed here.
    # The custom config file tells the app to READ this variable.
    - SECURITY_API_KEYS=${SECURITY_API_KEYS:-}
  volumes:
    - /dev/shm:/dev/shm  # Chromium performance
  deploy:
    resources:
      limits:
        memory: 4G
      reservations:
        memory: 1G
  restart: unless-stopped
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:11235/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    start_period: 40s
  user: "appuser"

services:
  crawl4ai:
    image: ${IMAGE:-unclecode/crawl4ai:${TAG:-latest}}
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_TYPE: ${INSTALL_TYPE:-default}
        ENABLE_GPU: ${ENABLE_GPU:-false}
    
    # This is the critical new section that links your two files
    volumes:
      # This line mounts your custom config file, overwriting the default one.
      - ./config/production.yml:/app/config.yml
    
    # Inherit shared config
    <<: *base-config
