# Application Configuration
app:
  title: "Crawl4AI API"
  version: "1.0.0"
  host: "0.0.0.0"
  port: 8020
  reload: False
  timeout_keep_alive: 300

# Default LLM Configuration - THIS SECTION WAS MISSING
llm:
  provider: "deepinfra/zai-org/GLM-4.6" # A default is required

# Redis Configuration
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: ""

# Rate Limiting Configuration
rate_limiting:
  enabled: True
  default_limit: "1000/minute"
  storage_uri: "memory://"

# Security Configuration - WITH OUR CHANGE
security:
  enabled: true # Master toggle is now ON
  api_keys_env: "SECURITY_API_KEYS" # Tells the app which env var holds the keys
  jwt_enabled: false
  https_redirect: false
  trusted_hosts: ["*"]
  headers:
    x_content_type_options: "nosniff"
    x_frame_options: "DENY"
    content_security_policy: "default-src 'self'"
    strict_transport_security: "max-age=63072000; includeSubDomains"

# Crawler Configuration
crawler:
  memory_threshold_percent: 95.0
  rate_limiter:
    base_delay: [1.0, 2.0]
  timeouts:
    stream_init: 30.0
    batch_process: 300.0

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Observability Configuration
observability:
  prometheus:
    enabled: True
    endpoint: "/metrics"
  health_check:
    endpoint: "/health"
